account_id = "" # set via CLOUDFLARE_ACCOUNT_ID env var or `wrangler whoami`
name = "void-td-codes"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CODES"
id = "14db469853ef4937899bdc182a78b60c"
